"""update models to match ERD

Revision ID: b387d4c931d9
Revises: 6f076f69c37a
Create Date: 2025-12-17 16:25:19.711911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b387d4c931d9'
down_revision: Union[str, Sequence[str], None] = '6f076f69c37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loan_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_loans_asset_id_assets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_asset_loans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_loans'))
    )
    op.create_index(op.f('ix_asset_loans_asset_id'), 'asset_loans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_loans_loan_status'), 'asset_loans', ['loan_status'], unique=False)
    op.create_index(op.f('ix_asset_loans_user_id'), 'asset_loans', ['user_id'], unique=False)
    op.drop_index(op.f('ix_borrows_asset_id'), table_name='borrows')
    op.drop_index(op.f('ix_borrows_status'), table_name='borrows')
    op.drop_index(op.f('ix_borrows_user_id'), table_name='borrows')
    op.drop_table('borrows')
    op.add_column('assets', sa.Column('asset_code', sa.String(length=100), nullable=False))
    op.add_column('assets', sa.Column('current_status', sa.String(length=50), nullable=False))
    op.add_column('assets', sa.Column('asset_condition', sa.String(length=50), nullable=False))
    op.add_column('assets', sa.Column('pic_user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('ix_assets_current_status'), 'assets', ['current_status'], unique=False)
    op.create_index(op.f('ix_assets_pic_user_id'), 'assets', ['pic_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_assets_pic_user_id_users'), 'assets', 'users', ['pic_user_id'], ['id'])
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'condition')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('assets', sa.Column('condition', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='assetstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_assets_pic_user_id_users'), 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_pic_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_current_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.drop_column('assets', 'pic_user_id')
    op.drop_column('assets', 'asset_condition')
    op.drop_column('assets', 'current_status')
    op.drop_column('assets', 'asset_code')
    op.create_table('borrows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('borrowed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('returned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'RETURNED', 'OVERDUE', name='borrowstatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_borrows_asset_id_assets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_borrows_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrows'))
    )
    op.create_index(op.f('ix_borrows_user_id'), 'borrows', ['user_id'], unique=False)
    op.create_index(op.f('ix_borrows_status'), 'borrows', ['status'], unique=False)
    op.create_index(op.f('ix_borrows_asset_id'), 'borrows', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_asset_loans_user_id'), table_name='asset_loans')
    op.drop_index(op.f('ix_asset_loans_loan_status'), table_name='asset_loans')
    op.drop_index(op.f('ix_asset_loans_asset_id'), table_name='asset_loans')
    op.drop_table('asset_loans')
    # ### end Alembic commands ###
